<?php

namespace app\models\work;

use app\models\common\CertificatTemplates;
use app\models\components\FileWizard;


use Yii;

/**
 * This is the model class for table "certificat_templates".
 *
 * @property int $id
 * @property string $name
 * @property string $path
 *
 * @property Certificat[] $certificats
 */
class CertificatTemplatesWork extends CertificatTemplates
{
    public $templateFile;
    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'certificat_templates';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['name', 'path'], 'required'],
            [['name', 'path'], 'string', 'max' => 1000],
            [['templateFile'], 'file', 'extensions' => 'jpg, png, pdf, jpeg, gif', 'skipOnEmpty' => true],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'name' => 'Name',
            'path' => 'Path',
        ];
    }

    /**
     * Gets query for [[Certificats]].
     *
     * @return \yii\db\ActiveQuery
     */
    public function getCertificats()
    {
        return $this->hasMany(Certificat::className(), ['certificat_template_id' => 'id']);
    }

    public function beforeSave($insert)
    {
        $this->uploadTemplateFile();
        return parent::beforeSave($insert); // TODO: Change the autogenerated stub
    }

    public function uploadTemplateFile()
    {
        $path = '@app/upload/files/certificat_templates/';
        $filename = 'Шаблон "'.$this->name.'"';
        $res = mb_ereg_replace('[ ]{1,}', '_', $filename);
        $res = mb_ereg_replace('[^а-яА-Я0-9._]{1}', '', $res);
        $res = FileWizard::CutFilename($res);
        $this->path = $res . '.' . $this->templateFile->extension;
        $this->templateFile->saveAs( $path . $res . '.' . $this->templateFile->extension);
    }
}
