<?php

namespace app\models\work;

use app\models\common\Certificat;
use app\models\common\ForeignEventParticipants;
use app\models\components\PdfWizard;
use app\models\work\CertificatTemplatesWork;
use app\models\work\TrainingGroupParticipantWork;

use Yii;
use yii\helpers\Html;
use ZipStream\ZipStream;


class CertificatWork extends Certificat
{
    public $group_id;
    public $participant_id;

    public $boobs;

    public function rules()
    {
        return [
            [['certificat_number', 'certificat_template_id', 'training_group_participant_id'], 'required'],
            [['certificat_number', 'certificat_template_id', 'training_group_participant_id', 'group_id'], 'integer'],
            [['participant_id', 'boobs'], 'safe'],
            [['certificat_template_id'], 'exist', 'skipOnError' => true, 'targetClass' => CertificatTemplatesWork::className(), 'targetAttribute' => ['certificat_template_id' => 'id']],
            [['training_group_participant_id'], 'exist', 'skipOnError' => true, 'targetClass' => TrainingGroupParticipantWork::className(), 'targetAttribute' => ['training_group_participant_id' => 'id']],
        ];
    }


    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'certificat_number' => 'Номер сертификата',
            'certificatLongNumber' => 'Номер сертификата',
            'certificatView' => 'Номер сертификата',
            'certificat_template_id' => 'Шаблон сертификата',
            'certificatTemplateName' => 'Шаблон сертификата',
            'training_group_participant_id' => 'Учащийся',
            'participantName' => 'Учащийся',
            'participantGroup' => 'Учебная группа учащегося',
            'pdfFile' => 'Сертификат',
        ];
    }

    public function getCertificatLongNumber()
    {
        $result = sprintf('%06d', $this->certificat_number);
        return $result;
    }

    public function getCertificatView()
    {
        return Html::a($this->getCertificatLongNumber(), \yii\helpers\Url::to(['certificat/view', 'id' => $this->id]));
    }

    public function getPdfFile()
    {
        $result = Html::a("Сгенерировать и выгрузить", \yii\helpers\Url::to(['certificat/generation-pdf', 'certificat_id' => $this->id]), ['class'=>'btn btn-success']);
        return $result;
    }

    public function  getParticipantGroup()
    {
        $part = TrainingGroupParticipantWork::find()->where(['id' => $this->training_group_participant_id])->one();
        $result = Html::a($part->trainingGroupWork->number, \yii\helpers\Url::to(['training-group/view', 'id' => $part->training_group_id]));
        return $result;
    }

    public function getParticipantName()
    {
        $part = TrainingGroupParticipantWork::find()->where(['id' => $this->training_group_participant_id])->one();
        $result = Html::a($part->participantWork->fullName, \yii\helpers\Url::to(['foreign-event-participants/view', 'id' => $part->participant_id]));
        return $result;
    }

    public function getCertificatTemplateName()
    {
        $templates = CertificatTemplatesWork::find()->where(['id' => $this->certificat_template_id])->one();
        $result = Html::a($templates->name, \yii\helpers\Url::to(['certificat-templates/view', 'id' => $templates->id]));
        return $result;
    }

    public function mass_save()
    {
        $allCert = CertificatWork::find()->orderBy(['certificat_number' => SORT_DESC])->all();
        $startNumber = $allCert[0]->certificat_number + 1;
        $tc = 0;
        $zip = new ZipStream('test.zip');
        if ($this->participant_id != null)
        {
            for ($i = 0; $i < count($this->participant_id); $i++)
            {
                if ($this->participant_id[$i] != 0)
                {
                    $cert = new CertificatWork();
                    $cert->certificat_number = $startNumber + $tc;
                    $cert->certificat_template_id = $this->certificat_template_id;
                    $cert->training_group_participant_id = $this->participant_id[$i];
                    $cert->save();
                    $zip->addFileFromPath($cert->certificat_number.'.png', Yii::$app->basePath.'/templates/logo.png');
                    //var_dump($cert->boobs);
                    $tc++;
                }
                
            }
        }
        $zip->finish();
    }


    public function afterSave($insert, $changedAttributes)
    {
        //var_dump($this->id);
        $this->boobs = PdfWizard::DownloadCertificat($this->id);
        parent::afterSave($insert, $changedAttributes); // TODO: Change the autogenerated stub

        //
    }
}
