<?php

namespace app\models\work;

use app\models\common\Entry;
use Yii;


class EntryWork extends Entry
{
    public $name; //общее имя для всех объектов записи
    public $price; //общая цена для всех объектов
    public $create_date; //общая дата производства для всех объектов
    public $lifetime; //общая дата окончания эксплуатации для всех объектов
    public $expirationDate; //общая дата окончания срока годности для всех объектов
    public $inventory_number; //инвентарный номер (только для ОС)

    public function rules()
    {
        return [
            [['name', 'create_date', 'lifetime', 'expirationDate'], 'string'],
            [['object_id', 'amount', 'price', 'inventory_number'], 'integer'],
            [['object_id'], 'exist', 'skipOnError' => true, 'targetClass' => MaterialObjectWork::className(), 'targetAttribute' => ['object_id' => 'id']],
        ];
    }

    public function fill()
    {
        $obj = MaterialObjectWork::find()->where(['id' => $this->object_id])->one();
        $this->name = $obj->name;
        $this->price = $obj->price;
        $this->create_date = $obj->create_date;
        $this->lifetime = $obj->lifetime;
        $this->expirationDate = $obj->expirationDate;
        $this->inventory_number = $obj->inventory_number;
    }

	public function getObjectWork()
    {
        return $this->hasOne(MaterialObjectWork::className(), ['id' => 'object_id']);
    }

    public function afterSave($insert, $changedAttributes)
    {
        parent::afterSave($insert, $changedAttributes); // TODO: Change the autogenerated stub
        for ($i = $this->object_id; $i < $this->object_id + $this->amount; $i++)
        {
            $object = MaterialObjectWork::find()->where(['id' => $i])->one();
            $object->name = $this->name;
            $object->price = $this->price;
            $object->create_date = $this->create_date;
            $object->lifetime = $this->lifetime;
            $object->expirationDate = $this->expirationDate;
            $object->inventory_number = $this->inventory_number;
            $object->save();
        }
    }
}
