<?php

namespace app\models\work;

use app\models\common\InvoiceEntry;
use Yii;


class InvoiceEntryWork extends InvoiceEntry
{
	public function getEntryWork()
    {
        return $this->hasOne(EntryWork::className(), ['id' => 'entry_id']);
    }

    /**
     * Gets query for [[Invoice]].
     *
     * @return \yii\db\ActiveQuery
     */
    public function getInvoiceWork()
    {
        return $this->hasOne(InvoiceWork::className(), ['id' => 'invoice_id']);
    }


    public function afterDelete()
    {
        $objectEntries = ObjectEntryWork::find()->where(['entry_id' => $this->entry_id])->all();
        foreach ($objectEntries as $one)
        {
            $object = MaterialObjectWork::find()->where(['id' => $one->material_object_id])->one();
            $entry = EntryWork::find()->where(['id' => $one->entry_id])->one();
            if ($one !== null) $one->delete();
            if ($object !== null) $object->delete();
            if ($entry !== null) $entry->delete();
        }

        return parent::afterDelete();
    }


    public function beforeDelete()
    {
        

        return parent::beforeDelete(); // TODO: Change the autogenerated stub
    }
}
