<?php

namespace app\models\work;

use app\models\common\Invoice;
use app\models\work\EntryWork;
use app\models\work\InvoiceEntryWork;
use yii\helpers\Html;
use Yii;


class InvoiceWork extends Invoice
{
	public $objects; //записи об объектах

	public function rules()
    {
        return [
            [['number', 'contractor_id', 'date'], 'required'],
            [['contractor_id', 'type'], 'integer'],
            [['date'], 'safe'],
            [['number'], 'string', 'max' => 15],
            [['contractor_id'], 'exist', 'skipOnError' => true, 'targetClass' => CompanyWork::className(), 'targetAttribute' => ['contractor_id' => 'id']],
        ];
    }

    public function attributeLabels()
    {
        return [
            'number' => 'Номер накладной/акта',
            'contractor_id' => 'Контрагент',
            'date' => 'Дата',
            'type' => 'Type',
            'entries' => '',
        ];
    }

    public function getEntries()
    {
        $entries = InvoiceEntryWork::find()->where(['invoice_id' => $this->id])->all();
        $result = '';
        foreach ($entries as $entry)
        {
            $result .= '<b>'.$entry->entryWork->amount.'</b> '.$entry->entryWork->objectWork->name.'<br>';
            for ($i = $entry->entryWork->object_id; $i < $entry->entryWork->object_id + $entry->entryWork->amount; $i++)
            {
                $obj = MaterialObjectWork::find()->where(['id' => $i])->one();
                $result .= Html::a($obj->name, \yii\helpers\Url::to(['material-object/view', 'id' => $obj->id])).' - '.($i - $entry->entryWork->object_id + 1).'<br>';
            }

        }
        return $result;
    }

    public function afterSave($insert, $changedAttributes)
    {
    	parent::afterSave($insert, $changedAttributes); // TODO: Change the autogenerated stub
    	if ($this->objects !== null && $this->objects[0]->name != '')
    	{
            //сохраняем все объекты из динамической формы
    		foreach ($this->objects as $object)
            {
                $objId = -1;
                for ($i = 0; $i < $object->amount; $i++)
                {
                    $newObject = new MaterialObjectWork($object);
                    $newObject->number = $this->number;
                    $newObject->save();
                    if ($objId == -1) $objId = $newObject->id;
                }

                //создаем запись для накладной
                $entry = EntryWork::find()->where(['object_id' => $object->id])->one();
                if ($entry == null) $entry = new EntryWork();
                $entry->object_id = $objId;
                $entry->amount = $object->amount;
                $entry->save();

                //связываем запись и накладную/акт
                $invoiceEntry = InvoiceEntryWork::find()->where(['invoice_id' => $this->id])->andWhere(['entry_id' => $entry->id])->one();
                if ($invoiceEntry == null) $invoiceEntry = new InvoiceEntryWork();
                $invoiceEntry->invoice_id = $this->id;
                $invoiceEntry->entry_id = $entry->id;
                $invoiceEntry->save();
            }


    	}
    }
}
