<?php

namespace app\models\work;

use app\models\common\Invoice;
use Yii;


class InvoiceWork extends Invoice
{
	public $objects; //записи об объектах

	public function rules()
    {
        return [
            [['number', 'contractor_id', 'date'], 'required'],
            [['contractor_id', 'type'], 'integer'],
            [['date'], 'safe'],
            [['number'], 'string', 'max' => 15],
            [['contractor_id'], 'exist', 'skipOnError' => true, 'targetClass' => CompanyWork::className(), 'targetAttribute' => ['contractor_id' => 'id']],
        ];
    }

    public function afterSave($insert, $changedAttributes)
    {
    	parent::afterSave($insert, $changedAttributes); // TODO: Change the autogenerated stub
    	var_dump($this->objects[0]->characteristics);
    	if ($this->objects !== null && $this->objects[0]->name != '')
    	{
    		var_dump('lol');
    	}
    }
}
