<?php

namespace app\models\work;

use app\models\common\TrainingGroupParticipant;
use Yii;


class TrainingGroupParticipantWork extends TrainingGroupParticipant
{
    public $participant_name;

    public function getParticipantWork()
    {
        return $this->hasOne(ForeignEventParticipantsWork::className(), ['id' => 'participant_id']);
    }

    public function getTrainingGroupWork()
    {
        return $this->hasOne(TrainingGroupWork::className(), ['id' => 'training_group_id']);
    }

    public function beforeDelete()
    {
        $visits = VisitWork::find()->joinWith(['trainingGroupLesson trainingGroupLesson'])->where(['foreign_event_participant_id' => $this->participant_id])->andWhere(['trainingGroupLesson.training_group_id' => $this->training_group_id])->all();

        foreach ($visits as $visit) {
            $visit->delete();
        }
        return parent::beforeDelete(); // TODO: Change the autogenerated stub
    }
}
