<?php

namespace app\models\work;

use app\models\common\TrainingGroupParticipant;
use Yii;

/**
 * This is the model class for table "training_group_participant".
 *
 * @property int $id
 * @property int $participant_id
 * @property string|null $certificat_number
 * @property int|null $send_method_id
 * @property int $training_group_id
 * @property int $status
 *
 * @property ForeignEventParticipants $participant
 * @property SendMethod $sendMethod
 * @property TrainingGroup $trainingGroup
 */
class TrainingGroupParticipantWork extends TrainingGroupParticipant
{
    public function getParticipantWork()
    {
        return $this->hasOne(ForeignEventParticipantsWork::className(), ['id' => 'participant_id']);
    }

    public function getTrainingGroupWork()
    {
        return $this->hasOne(TrainingGroupWork::className(), ['id' => 'training_group_id']);
    }

    public function beforeDelete()
    {
        $visits = VisitWork::find()->joinWith(['trainingGroupLesson trainingGroupLesson'])->where(['foreign_event_participant_id' => $this->participant_id])->andWhere(['trainingGroupLesson.training_group_id' => $this->training_group_id])->all();

        foreach ($visits as $visit) {
            $visit->delete();
        }
        return parent::beforeDelete(); // TODO: Change the autogenerated stub
    }
}
