<?php

namespace app\models\common;

use Yii;
use yii\helpers\Html;

/**
 * This is the model class for table "branch".
 *
 * @property int $id
 * @property string $name
 */
class Branch extends \yii\db\ActiveRecord
{
    public $auditoriums;
    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'branch';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['name'], 'required'],
            [['name'], 'string', 'max' => 1000],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'name' => 'Название отдела',
            'auditoriumsList' => 'Список помещений',
            'workerList' => 'Список сотрудников',
        ];
    }

    public function getAuditoriumsList()
    {
        $auds = Auditorium::find()->where(['branch_id' => $this->id])->all();
        $result = '';
        foreach ($auds as $aud)
        {
            $result .= $aud->name.'<br>';
        }
        return $result;
    }

    public function getWorkerList()
    {
        $workers = People::find()->where(['branch_id' => $this->id])->all();
        $result = '';
        foreach ($workers as $worker)
        {
            $result .= Html::a($worker->fullName, \yii\helpers\Url::to(['people/view', 'id' => $worker->id])).'<br>';
        }
        return $result;
    }

    public function afterSave($insert, $changedAttributes)
    {
        parent::afterSave($insert, $changedAttributes); // TODO: Change the autogenerated stub
        if ($this->auditoriums !== null && $this->auditoriums[0]->name !== '')
        {
            foreach ($this->auditoriums as $auditorium)
            {
                $newAuds = new Auditorium();
                $newAuds->branch_id = $this->id;
                $newAuds->name = $auditorium->name;
                $newAuds->save(false);
            }
        }
    }
}
